version: '3'
volumes: 
  dados:

networks: 
  database:

services:
  mssql:
    image: microsoft/mssql-server-linux
    container_name: mssql
    ports:
      - 1433:1433
      - 1434:1434
    networks:
      - database
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'root@123'
